version: "3.8"
services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=ec2,s3    # services ec2 and s3 will be started
      - DEBUG=1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"